import { useQuery } from '@tanstack/react-query'
import { ArrowDownRight, ArrowUpRight, CreditCard, IndianRupee, Package, Users } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import { api } from '@/lib/api-client'
import { currency } from '@/lib/utils'
import { Card, CardContent, CardHeader, Skeleton } from '@/components/ui'

const fallback = [{ name: 'Jan', sales: 240000 }, { name: 'Feb', sales: 310000 }, { name: 'Mar', sales: 280000 }, { name: 'Apr', sales: 390000 }, { name: 'May', sales: 450000 }, { name: 'Jun', sales: 510000 }]
const metrics = [{ label: 'Sales this month', value: 524800, delta: '12.5%', icon: IndianRupee, up: true }, { label: 'Outstanding receivables', value: 186400, delta: '4.2%', icon: CreditCard, up: false }, { label: 'Products in stock', value: 1248, delta: '8 added', icon: Package, up: true }, { label: 'Active customers', value: 428, delta: '24 new', icon: Users, up: true }]
export function DashboardPage() {
  const { data, isLoading } = useQuery({ queryKey: ['dashboard'], queryFn: async () => (await api.get('/dashboard')).data.data, retry: false })
  const chart = data?.salesTrend ?? fallback
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-slate-900">Good morning, Admin</h1><p className="mt-1 text-sm text-slate-500">Here is an overview of your business today.</p></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => <Card key={metric.label}><CardContent className="p-5">{isLoading ? <Skeleton className="h-20" /> : <><div className="flex justify-between"><span className="text-sm text-slate-500">{metric.label}</span><metric.icon className="size-4 text-teal-700" /></div><p className="mt-3 text-2xl font-semibold text-slate-900">{metric.label.includes('stock') || metric.label.includes('customers') ? metric.value.toLocaleString() : currency(metric.value)}</p><span className={`mt-2 inline-flex items-center gap-1 text-xs ${metric.up ? 'text-emerald-600' : 'text-rose-600'}`}>{metric.up ? <ArrowUpRight className="size-3" /> : <ArrowDownRight className="size-3" />}{metric.delta} <span className="text-slate-400">vs last month</span></span></>}</CardContent></Card>)}</section><section className="grid gap-6 xl:grid-cols-3"><Card className="xl:col-span-2"><CardHeader><div><h2 className="font-semibold text-slate-900">Sales performance</h2><p className="text-sm text-slate-500">Revenue over the last six months</p></div></CardHeader><CardContent><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="sales" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#0f766e" stopOpacity=".28" /><stop offset="100%" stopColor="#0f766e" stopOpacity="0" /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 12 }} /><Tooltip formatter={(value) => currency(Number(value))} /><Area type="monotone" dataKey="sales" stroke="#0f766e" strokeWidth={2.5} fill="url(#sales)" /></AreaChart></ResponsiveContainer></div></CardContent></Card><Card><CardHeader><h2 className="font-semibold text-slate-900">Needs attention</h2></CardHeader><CardContent className="space-y-4">{[['12 overdue invoices', '₹84,200 pending', 'rose'], ['5 low stock items', 'Reorder recommended', 'amber'], ['3 purchase orders due', 'Due this week', 'teal']].map(([title, detail, color]) => <div key={title} className="flex gap-3"><div className={`mt-1 size-2 rounded-full bg-${color}-500`} /><div><p className="text-sm font-medium text-slate-800">{title}</p><p className="text-xs text-slate-500">{detail}</p></div></div>)}</CardContent></Card></section></div>
}
