import { useQuery } from '@tanstack/react-query'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Plus, Search, SlidersHorizontal } from 'lucide-react'
import { api } from '@/lib/api-client'
import { Badge, Button, Card, CardContent, Input, Skeleton, Table } from '@/components/ui'

type Config = { title: string; endpoint: string; singular: string; fields: string[] }
const configs: Record<string, Config> = {
  customers: { title: 'Customers', singular: 'Customer', endpoint: '/customers', fields: ['name', 'phone', 'email', 'gstin', 'creditLimit'] },
  suppliers: { title: 'Suppliers', singular: 'Supplier', endpoint: '/suppliers', fields: ['name', 'phone', 'email', 'gstin', 'payableBalance'] },
  products: { title: 'Products', singular: 'Product', endpoint: '/products', fields: ['name', 'sku', 'barcode', 'salePrice', 'stockOnHand'] },
  categories: { title: 'Product categories', singular: 'Category', endpoint: '/categories', fields: ['name', 'description', 'active'] },
  warehouses: { title: 'Warehouses', singular: 'Warehouse', endpoint: '/warehouses', fields: ['name', 'code', 'city', 'isDefault'] },
}
const title = (value: string) => value.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase())
export function EntityListPage({ kind }: { kind: keyof typeof configs }) {
  const config = configs[kind]; const { data, isLoading } = useQuery({ queryKey: [kind], queryFn: async () => (await api.get(config.endpoint, { params: { size: 50 } })).data, retry: false })
  const rows = data?.content ?? data?.data?.content ?? data?.data ?? data ?? []
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold text-slate-900">{config.title}</h1><p className="mt-1 text-sm text-slate-500">Manage your {config.title.toLowerCase()} and records.</p></div><Link className="inline-flex h-9 items-center gap-2 rounded-lg bg-teal-700 px-4 text-sm font-medium text-white hover:bg-teal-800" to={`/${kind}/new`}><Plus className="size-4" />Add {config.singular}</Link></div><Card><CardContent className="p-4"><div className="mb-4 flex gap-3"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-2.5 size-4 text-slate-400" /><Input className="pl-9" placeholder={`Search ${config.title.toLowerCase()}…`} /></div><Button variant="outline"><SlidersHorizontal className="size-4" />Filters</Button></div>{isLoading ? <div className="space-y-3">{[1, 2, 3, 4].map((id) => <Skeleton key={id} className="h-12 w-full" />)}</div> : <Table><thead><tr className="border-b border-slate-200">{config.fields.map((field) => <th key={field} className="px-3 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">{title(field)}</th>)}<th /></tr></thead><tbody>{rows.length ? rows.map((row: Record<string, unknown>) => <tr key={String(row.id)} className="border-b border-slate-100 hover:bg-slate-50">{config.fields.map((field) => <td key={field} className="px-3 py-3 text-slate-700">{typeof row[field] === 'boolean' ? <Badge className={row[field] ? 'bg-emerald-100 text-emerald-700' : ''}>{row[field] ? 'Active' : 'Inactive'}</Badge> : String(row[field] ?? '—')}</td>)}<td className="px-3 py-3 text-right"><Link className="text-sm font-medium text-teal-700 hover:underline" to={`/${kind}/${row.id}`}>View</Link></td></tr>) : <tr><td colSpan={config.fields.length + 1} className="py-16 text-center text-sm text-slate-500">No {config.title.toLowerCase()} found. Create your first one to get started.</td></tr>}</tbody></Table>}</CardContent></Card></div>
}
export function EntityFormPage({ kind }: { kind: keyof typeof configs }) {
  const config = configs[kind]; const navigate = useNavigate()
  return <div className="max-w-3xl space-y-6"><div><h1 className="text-2xl font-semibold text-slate-900">New {config.singular}</h1><p className="mt-1 text-sm text-slate-500">Add details for this {config.singular.toLowerCase()}.</p></div><Card><CardContent className="p-6"><form className="grid gap-4 sm:grid-cols-2" onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); await api.post(config.endpoint, Object.fromEntries(form)); navigate(`/${kind}`) }}>{config.fields.filter((field) => field !== 'active' && field !== 'isDefault').map((field) => <label key={field} className="space-y-1.5 text-sm font-medium text-slate-700">{title(field)}<Input name={field} type={field.includes('Limit') || field.includes('Price') ? 'number' : 'text'} required={field === 'name'} /></label>)}<div className="col-span-full flex justify-end gap-3 border-t border-slate-100 pt-5"><Button type="button" variant="outline" onClick={() => navigate(-1)}>Cancel</Button><Button type="submit">Save {config.singular}</Button></div></form></CardContent></Card></div>
}
export function EntityDetailPage({ kind }: { kind: keyof typeof configs }) { const { id } = useParams(); const config = configs[kind]; const { data } = useQuery({ queryKey: [kind, id], queryFn: async () => (await api.get(`${config.endpoint}/${id}`)).data }); const item = data?.data ?? data; return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-slate-900">{item?.name ?? config.singular}</h1><p className="mt-1 text-sm text-slate-500">{config.singular} record</p></div><Card><CardContent className="grid gap-5 p-6 sm:grid-cols-2">{config.fields.map((field) => <div key={field}><p className="text-xs uppercase tracking-wide text-slate-500">{title(field)}</p><p className="mt-1 text-sm font-medium text-slate-800">{String(item?.[field] ?? '—')}</p></div>)}</CardContent></Card></div> }
